version: '3'

services:

    reverse-proxy:
        image: nginx:latest
        container_name: reverse_proxy
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
    
    server:
        image: server
        container_name: server
        build:
            context: ./server
        ports:
            - 5000:5000
        restart: on-failure